---
- hosts: all
  become: yes
  tasks:
    # Installing for Ubuntu #
  - name: Install apache and update
    apt:
      name: apache2
      state: present
      update_cache: yes
    when: ansible_os_family == "Debain"
    # Need to Restart the service for UBUNTU #
    notify:
    - restart apache
    # Installing for RedHat #
  - name: Install httpd
    yum:
      name: httpd
      state: present
      enabled: yes
    when: ansible_os_family == "RedHat"
    # Need to Restart the service for REDHAT #
    notify:
    - restart httpd
    # Installing the php packages for Ubuntu #
  - name: Install php packags
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
    when: ansible_os_family == "Debain"
      # Installing the PHP packages for Redhat #
  - name: Install php packages for RedHat
    yum:
      name:
      state: present
    with_items:
      - php
      - php-mysql
    when: ansible_os_family == "RedHat"
  - name: download the web page
    get_url:
      url: https://raw.githubusercontent.com/sandeepmchary/Ansible1/master/lamp%20for%20both%20OS/Info.php
      dest: /var/www/html/info.php
    notify:
    - restart apache
    - restart httpd
  handlers:
    - name: restart apache
      service:
        name: apache2
        enabled: yes
        state: restarted
    when: ansible_os_family == "Debian"
    - name: restart httpd
      service:
        name: httpd
        enabled: yes
        state: restarted
    when: ansible_os_family == "RedHat"


      

