---
- hosts: all
  become: yes
  roles:
    - geerlingguy.java
    - idealista tomcat-role
  tasks:
  - name: copy war files
    copy:
      src: gameoflife.war
      dest: /opt/tomcat/webapps/gameoflife.war
  handlers:
  - name: restart tomcat
    service:
      name: tomcat
      state: restarted
      enabled: yes
      



  
