---
- hosts: all
  become: yes
  roles:
    - geerlingguy.java
    - idealista.tomcat-role
    tasks:
    - name: copy war file
      copy:
      src: gameoflife.war
      dest: /usr/local/tomat/webapss


  
