---
- hosts: all
  become: yes
  tasks:
  - name: update package and install apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
    notify:
       - Restart apache2
  - name: Restart the apache after installation
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: Install php Packages
    apt:
       name: "{{ item }}"
       state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
  handlers:
  - name: Restart apache2
    service:
      name: apache2
      state: restarted
      enabled: yes
  
