---
# tasks file for default
- name: Install apache server
  package:
    name: "{{ pack_name }}"
    state: present
  notify:
    - restart apache
- name: Install php packages 
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_packages }}"
  notify:
  - restart apache
- name: download the webpage
  get_url:
    url: https://raw.githubusercontent.com/sandeepmchary/Ansible1/master/lamp%20for%20both%20OS/Info.php
    dest: /var/www/html/info.php
  notify:
  - restart apache
